### ISSUE TITLE
Server: APIの処理を仕様に近づける

### ISSUE THREAD

**Issue by fumontr** [shortintern2020-C-cryptograph/TeamF#37]
## 概要

GET /dialogなど、offset, limitを利用したSELECTなどをできるようにする。
## 目的

現状DBを叩く際の処理が仕様通りでないので変更する。
## タスク

- [x] offset, limitを利用した範囲SELECT
- [ ] q(query)を利用したLIKE SELECT
- [x] style, genreなどを利用した条件付きSELECT
- [ ] sortを用いて好みのソート順で取得する（もしくは取得結果をソートする？）

**Comment by nunorlabo** [comment]
Must haveな部分はDoneしたので一旦閉じます。
