### ISSUE TITLE
Frontend: マウスドラッグ

### ISSUE THREAD

**Issue by ritsu2891** [shortintern2020-C-cryptograph/TeamF#63]
## 概要

マウスドラッグで画面位置を移動させるようにする。

## 目的

セリフやコメントを一覧で表示するような画面を作る事を考えているが、一画面に表示できるオブジェクトの数は限られているためドラッグで画面位置を移動し別のオブジェクトを表示できるようにしたい。

## 考慮すべきポイント
今回のアプリケーションでは以下のような特徴があり、上記を実現しようと考えた際にそれぞれ考慮すべき点がある。

### 表示する要素を全てCanvasで壁画している。
Canvasで壁画するのに用いているPIXIおよびmatterのオブジェクトはメモリを食うので、画面外に行った壁画する必要の無いオブジェクトは即座にメモリから消去されるのが望ましい。保持するにしても、壁画に必要なセリフなどのデータのみにとどめる。もしくは再度フェッチしても良い。

### 今回はオブジェクトの動きに「特定のポイントに向かって重力が発生しているような動作」をさせてふわふわした動きを実現している。
これが肝要である。まず、ふわふわした動きを実現するのに費やしている***計算コストがかなり高い***。手元のPCでは、スケールのアニメーションなどを加えていない状態でせいぜい20個のオブジェクトを同時に演算させるのが限界である。よって画面外に出たオブジェクトのふわふわした動き、すなわち物理演算は即座に停止し同時に演算を行っているオブジェクトを特定の数に収める必要がある。これは上記一つ目のポイントと同様に、画面外に出たオブジェクトについては即座に削除すべきと言う考えに帰結する。さらに、物理演算を開始するタイミングについても考慮すべき必要がある。不自然なタイミングで動きを開始しないよう、画面端にギリギリで演算を開始するなどの工夫が要る。
さらに、現在の実装では特定のポイントに向かって移動するような動きのみ実現しているので、仮にこれをこのまま用いる場合は画面を移動した際にオブジェクトが向かう「特定のポイント」も移動していかないとオブジェクトがあらぬ方向に向かってしまう。また、ポイントを移動した際のオブジェクトの動き方を見て重力の受けやすさなどを調整する必要がある。（オブジェクト同士がぶつかることによってもオブジェクトが移動する）

### 中心に最初のオブジェクトを据えて同心円状にオブジェクトを配置していくようなレイアウトを取っている。
この特徴により、順序（例：新旧）のあるオブジェクトをどのように配置するかという問題が発生する。単純な上下スクロールであれば上から順に新しい方、などと決められるが、今回のレイアウトの場合どうだろうか。同心円状に、中心から外側に向かって新しい、と決めてしまう事もできる。その場合、最初の円周の小さいうちは良いが、円周が大きくなると順序の近い（例：時刻の近い）オブジェクトを閲覧するのに円上にドラッグして閲覧することになり操作しづらいのではないか。
以上のような理由から同心円状に順序のあるオブジェクトを配置するのは適切でないと考えられる。一方、同心円状にオブジェクトを配置するレイアウトは面白みがあり、良いと考えている。どうするか、議論の余地がある。
***順序のある配置をそもそもしない*** という選択肢も考えられる。作品との予期せぬ出会いが1つのコンセプトであるから、セリフについてはランダムに表示して良いような気がするし、セリフに対する思い入れのコメントは毎回ランダムで表示された方が色々なコメントを見られてこれはこれでいいような気がする。時系列である必要はない。ただ、ランダムの場合同じような場所にドラッグさせたはずなのに全く違うオブジェクトが表示されて違和感を感じるかもしれないが･･･。悩むな。

## タスク

- [ ] オブジェクトと壁画領域のマッピングをどうするか考える（同心円状か、そもそもランダムにしてしまうか･･･） 
- [ ] マウスドラッグを検知して、PIXIのカメラ位置に反映させる
- [ ] 壁画領域の変化に応じてフェッチ・フェッチしたデータの壁画を行うようにする
- [ ] 壁画領域外のオブジェクトを削除するようにする

**Comment by takapiro99** [comment]
> ただ、ランダムの場合同じような場所にドラッグさせたはずなのに全く違うオブジェクトが表示され

これは、毎回2回目以降の表示がランダムになるっていうことかな(?)

同心円状のほうが良いと思います！順序は確かに難しいです。その時ごとに行った方向に、次のランダムなり何かしらの順序に従ってドーンと追加していけばよいのではないかと思います。ここの座標から追加する！みたいなのは難しいのかな(?)(わからん)

> 作品との予期せぬ出会いが1つのコンセプト  

まさにこれです
