### ISSUE TITLE
Frontend: APIのモック

### ISSUE THREAD

**Issue by ritsu2891** [shortintern2020-C-cryptograph/TeamF#64]
## 概要

そろそろフェッチしたデータに応じた壁画を行うプログラムを書き始めるので、開発中に用いるAPIのモックをどうするか決める。また、とりあえずMust Haveの機能に必要なAPIのモックを作る。

## 目的

バックエンドが完成していない状態でもフェッチを行うプログラムを開発できるようにするため。

## 候補
Reduxのチュートリアルでは[Mirage](https://miragejs.com/)というライブラリを使っていた。これだとモックの際（バックエンドにリクエストを投げない）のと本番の際（バックエンドにリクエストを投げる）でアプリケーション側のコードの変更を全くしなくて良いらしい。

## タスク

- [x] 方法（ライブラリ）を決定
- [x] APIモックの作成
- [x] axiosのラップ関数を作成し、APIを叩けるようにする

**Comment by takapiro99** [comment]
mirage, LGTM！

**Comment by ritsu2891** [comment]
2020/09/22 朝 決定事項
- Mirageを使います
