### ISSUE TITLE
Frontend: APIキーの隠蔽

### ISSUE THREAD

**Issue by ritsu2891** [shortintern2020-C-cryptograph/TeamF#66]
## 概要

firebaseのAPIキーがリポジトリにそのまま上がっているのはよろしく無くなんじゃないかと思われる...。

## 目的

よほど大丈夫だとは思うが、念のため隠しておかないといけない気がする。

## タスク

- [ ] リポジトリから削除
- [ ] APIキーの変更
- [ ] .envファイルを使う

**Comment by takapiro99** [comment]
各所で言われていますが、APIKey自体が公開されていることは ”セキュリティ的には” 問題ないようです。
https://stackoverflow.com/questions/37482366/is-it-safe-to-expose-firebase-apikey-to-the-public
https://qiita.com/hoshymo/items/e9c14ed157200b36eaa5

しかし、今後変更されるかもしれないものを直書きしているという点ではよくないと思うので、envに移すほうがよさそうです(今後、ステージング環境など、複数のfirebase projectを使う場合が出てきたときにも困りそう)

キーを一つずつ環境変数に設定することもできますが、全体をstringにしてJSON.parse()するのどうでしょう

**Comment by ritsu2891** [comment]
> 各所で言われていますが、APIKey自体が公開されていることは ”セキュリティ的には” 問題ないようです。

なるほど、FirebaseのAPIキーは公開前提なんですね。よく考えたら最終的にはブラウザに配信するスクリプトにこの値が入ってないと認証できませんもんね。

> 全体をstringにしてJSON.parse()するのどうでしょう

その方がいいですね。そうしましょう。

**Comment by takapiro99** [comment]
これうまくできなかったので、一旦パスします。
環境変数を読み込むところまでできましたが、JSON.parseで失敗しますダブルクオーテーションをエスケープなどしてもだめでした

**Comment by takapiro99** [comment]
一旦閉じます
