### ISSUE TITLE
Server: ポートとパスの変更

### ISSUE THREAD

**Issue by fumontr** [shortintern2020-C-cryptograph/TeamF#69]
## 概要

ポートとAPIのパスを変更する。
## 目的

ポートはフロントと被っているため。
パスはALBで振り分けを楽にするため。
## タスク

- [x] baseアドレスに/apiを追加
- [x] portを8080に変更

**Comment by takapiro99** [comment]
ありがとうございます！
フロントは3000でいいということでしょうか？
