### ISSUE TITLE
Frontend: セリフ・コメント表示における入力用要素の表示位置・大きさの払い出し

### ISSUE THREAD

**Issue by ritsu2891** [shortintern2020-C-cryptograph/TeamF#93]
## 概要

入力用`<textarea>`に指定する表示位置や大きさを計算し、指定できるようにする。

## 目的

- #65 実現のため（計算した位置・大きさを#71のコンポーネントに指定する）

## タスク

- [ ] 入力用モードの追加
- [ ] 計算した位置・大きさを公開プロパティに追加
- [ ] 渡したオブジェクトに計算した位置・大きさを上書きするようなメソッドを追加

**Comment by takapiro99** [comment]
multiple={true} みたいな感じで、複数行かそうでないかみたいなものを指定できるようにするといいかなって思ったんだけどどうでしょう

overflowしたときにvisibleなのかscrollなのか改行なのかっていうことですね

**Comment by ritsu2891** [comment]
どの入力エリアなのか（セリフ、作品名、コメント･･･）かの情報も払い出す

**Comment by ritsu2891** [comment]
`GraphicObject#calcTextAreas()`で以下の形式で払い出されます。
```javascript
[
 {
   type: 'dialog',
   position: {
     x: 0,
     y: 0
   },
   size: {
     width: 200,
     height: 100
   }
  }
]
```
